name: My first workflow

on: workflow_dispatch

jobs: 
    my-amazing-job:
      runs-on: ubunto-latest
      steps:
        - run: echo "The amazing job has started"
        - run: echo "The amazing job is complete"
